version: '3'

services:
#  apitodo:
#    depends_on:
#      - db
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: api-todo-docker
#    container_name: apitodo
#    restart: always # reiniciar el contenedor si se detiene
#    ports:
#      - "${PORT}:${PORT}"
#    # working_dir: /var/www/pokedex
#    environment:
#      NODE_ENV: ${NODE_ENV}
#      DB_NAME: ${DB_NAME}
#      DB_HOST: ${DB_HOST}
#      DB_PORT: ${DB_PORT}
#      DB_USERNAME: ${DB_USERNAME}
#      DB_PASSWORD: ${passwordTODO}
#    # volumes:
#    #   - ./:/var/www/pokedex

  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: api-todo
    volumes:
      - ./postgres:/var/lib/postgresql/data
